set -g mouse on
set -s set-clipboard on

set -s copy-command 'xclip -selection clipboard'
#set -s copy-command 'xsel -b'

set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g default-terminal "xterm-256color"
set -as terminal-overrides ",*:Tc"
