[window]
# Set to 1.0 for solid black, or lower (e.g., 0.9) for slight transparency
opacity = 1.0
# Adds the margins on the edges you requested
padding = { x = 15, y = 15 }

[font]
size = 13
builtin_box_drawing = true

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[colors.primary]
# Pure black background
background = '#000000'
foreground = '#fff1f3'

[colors.normal]
black   = '#000000'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#f38d70'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

[colors.bright]
black   = '#72696a'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#f38d70'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
